/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This document */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The contract */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/request-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email a one-time sign-in code
         * @description Always returns 200 with the same body whether or not the address has an account — this endpoint must not become an account-existence oracle.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a code for tokens */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        email: string;
                        code: string;
                        device_label?: string;
                        platform?: string;
                    };
                };
            };
            responses: {
                /** @description Signed in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tokens"];
                    };
                };
                /** @description Bad or expired code */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate tokens
         * @description Refresh tokens are single-use. Presenting one that has already been rotated revokes the whole session — we cannot distinguish replay from theft, so we assume theft.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description New tokens */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tokens"];
                    };
                };
                /** @description Sign in again */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke this device, or every device */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        all?: boolean;
                    };
                };
            };
            responses: {
                /** @description Revoked; effective on the next request */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devices signed in to this account */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sessions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The household: dancers managed, with derived studio affiliations */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Household */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dancers/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search dancers by name */
        get: {
            parameters: {
                query: {
                    q: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Matches */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dancers/{id}/awards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trophy case
         * @description Public, and honours the owner's per-card hide. Page with `cursor` (last id seen; ids only increase, so paging is stable under concurrent writes) and sync with `updated_since`.
         */
        get: {
            parameters: {
                query?: {
                    cursor?: number;
                    updated_since?: string;
                };
                header?: never;
                path: {
                    /** @description Numeric id or unique_id. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Awards */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            awards?: components["schemas"]["Award"][];
                            nextCursor?: number | null;
                        };
                    };
                };
                /** @description No such dancer */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dancers/{id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim a dancer profile
         * @description A second household claiming the same dancer contests both claims, which routes them to AwardHome and away from any studio.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        relationship?: string;
                        proof?: string;
                        studio_code?: string;
                    };
                };
            };
            responses: {
                /** @description Filed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Already claimed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Daily limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Event picker
         * @description Ranks the organizer's geocoded tour stops, other families' candidates, and canonical events. Pass lat/lng/date for the one-tap case, or q to search by name.
         */
        get: {
            parameters: {
                query?: {
                    lat?: number;
                    lng?: number;
                    date?: string;
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Options */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            options?: components["schemas"]["EventOption"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an event candidate (never a canonical event)
         * @description Send check_only:true to see likely duplicates without creating anything. Without confirm_new, a likely twin comes back as 409 with the duplicates instead of creating a second row.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        /** Format: date */
                        start_date: string;
                        /** Format: date */
                        end_date?: string;
                        city?: string;
                        state?: string;
                        venue?: string;
                        lat?: number;
                        lng?: number;
                        org_id?: number;
                        check_only?: boolean;
                        confirm_new?: boolean;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Likely duplicates offered */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status feed for this household */
        get: {
            parameters: {
                query?: {
                    cursor?: number;
                    updated_since?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Submissions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Submit a missing award
         * @description Idempotent on (user, client_submission_id): a retried offline upload returns the ORIGINAL row. group_size is required — it decides the canonical write path. The studio is derived from affiliation and is never accepted as free text.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        client_submission_id: string;
                        dancer_id: number;
                        event_id?: number;
                        event_candidate_id?: number;
                        upcoming_event_id?: number;
                        /** @description Only honoured when the dancer has more than one affiliation. */
                        studio_id?: number;
                        performance_name: string;
                        group_size: string;
                        place?: string;
                        category?: string;
                        award_type?: string;
                        age_division?: string;
                        teacher?: string;
                        choreographer?: string;
                        cast_names?: string[];
                        notes?: string;
                        /** @description From /event-sessions. Validated against the caller; an id belonging to another household is dropped, not rejected. */
                        event_session_id?: string;
                        /** @description Object key from an evidence upload, reused as the award card's photo. Enters moderation at 'pending' when the award is promoted — never published by submitting. */
                        card_photo_object_key?: string;
                        card_photo_media_type?: string;
                        /** @description Card acknowledgement. Also enters moderation at 'pending' on promotion. */
                        thank_you_note?: string;
                        /** @description Parent/guardian affirmation, or permission from everyone pictured. Recorded once per (uploader, dancer). */
                        card_consent_affirmed?: boolean;
                    };
                };
            };
            responses: {
                /** @description Idempotent replay of an earlier submission */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Daily limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request an upload grant
         * @description Two-step so the storage driver can change (local disk today, S3/R2 later) without the client changing. Evidence is private and is never share media.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Grant issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No such submission */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeem an upload grant with the file bytes
         * @description Send the raw bytes with the grant in the X-Upload-Grant header. The server identifies the file by its magic bytes, not by Content-Type, and strips EXIF/metadata before storing.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/octet-stream": string;
                };
            };
            responses: {
                /** @description Stored */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad grant or unsupported type */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Too large */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download evidence (uploader and reviewers only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The file, as an attachment */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found, or not yours */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose a correction to a published award
         * @description A proposal, never an edit. Only a household whose own dancer is on the award may file one.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        award_id: number;
                        dancer_id: number;
                        /** @enum {string} */
                        field: "performance_name" | "place" | "award_type" | "category" | "age_division";
                        proposed_value: string;
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description Filed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not your dancer's award */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Decisions and questions on this household's things
         * @description Deliberately not an engagement feed — decisions and questions only, the same rule push notifications follow.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Activity */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register for push */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        platform: string;
                        token: string;
                        preferences?: Record<string, never>;
                    };
                };
            };
            responses: {
                /** @description Registered */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open (or rejoin) the session for a weekend at one event
         * @description Get-or-create. A client that lost its local copy — reinstalled, switched devices mid-weekend — rejoins the same session rather than starting a second one, which is why the id is issued by the server rather than minted on the device. 201 when created, 200 when rejoining.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        event_id?: number;
                        event_candidate_id?: number;
                    };
                };
            };
            responses: {
                /** @description Existing session rejoined */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Session created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description An event is required */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What this session already knows
         * @description Suggested dancer, studio, teacher and choreographer from earlier submissions in the same batch — suggestions, never silently applied.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session context */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No such session */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Stable machine code. */
            error: string;
            /** @description Human-readable, safe to show a family. */
            message?: string;
        };
        Tokens: {
            accessToken?: string;
            refreshToken?: string;
            /** @description Access token lifetime in seconds. */
            expiresIn?: number;
        };
        Award: {
            id?: number;
            place?: string | null;
            performance_name?: string | null;
            award_type?: string | null;
            category?: string | null;
            age_division?: string | null;
            /** @description family_submitted | corroborated | studio_confirmed | source_verified. family_submitted awards are public but held out of competitive rankings. */
            verification_status?: string | null;
            event_name?: string | null;
            event_year?: number | null;
            org_name?: string | null;
            /** @description Independent dancers render as "Independent". */
            studio_name?: string | null;
            dancer_count?: number;
            /** @description Derived sync marker; pass back as updated_since. */
            updated_at?: string | null;
            /** @description overall | title | scholarship | special | studio. Decides how an empty placement reads. */
            award_class?: string | null;
            /** @description Placement as a reader should see it: ordinals normalised ("1" -> "1st"), and an empty placement rendered as "Winner" for scholarships/titles/special/studio awards — which have no rank — or "N/A" otherwise. Formatted by the same helper the web pages use; prefer this over `place`. */
            place_display?: string;
        };
        Submission: {
            id?: number;
            client_submission_id?: string;
            performance_name?: string;
            /** @enum {string} */
            group_size?: "solo" | "duet" | "trio" | "small_group" | "large_group" | "line" | "grand_line" | "production";
            /** @description 0 for group formats, always — the record is explicitly partial. */
            cast_complete?: number;
            /** @enum {string} */
            status?: "submitted" | "needs_info" | "accepted" | "rejected" | "withdrawn";
            verification_level?: string;
            award_id?: number | null;
        };
        EventOption: {
            /**
             * @description upcoming = the organizer's own announced tour stop; candidate = added by a family; event = canonical historical event.
             * @enum {string}
             */
            kind?: "upcoming" | "candidate" | "event";
            id?: number;
            name?: string;
            when?: string | null;
            where?: string | null;
            distance_miles?: number | null;
            note?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
