// Delete awards that are actually a results-table HEADER ROW imported as data
// ("Routine Name", "Studio", "Entry" as a performance name).
//
// These come from PDF extractors that fail to recognise a table header and
// fall through to their data-row branch. The NexStar case was the big one
// (5,502 rows; fixed at the source in extract_nexstar_pdfs.js and repaired by
// reconcile_nexstar_awards.js), but the class can recur in any org's extractor,
// and a single survivor is a fake award on a public page. This sweep is the
// backstop: cheap, idempotent, and safe to re-run.
//
// Safety: a row carrying real USER data (acknowledgements, photos, tombstones,
// hidden flags, or a dancer link a person made) is never deleted — it is
// reported instead, because a real family interaction means the row is not
// what it looks like. `award_dancers` rows with source='import' do NOT count:
// those are machine-generated by the same broken parse that created the fake
// award, so treating them as user data would make every artifact immortal.
//
// Usage (repo root; identical run on local and prod for data parity):
//   node scripts/purge_header_artifact_awards.js           # dry run
//   node scripts/purge_header_artifact_awards.js --apply
const { openDb } = require('../database');

// Exact header tokens only. Deliberately NOT a LIKE 'Routine Name%' sweep:
// a real routine could plausibly start with those words, and this script
// deletes. Extractor-specific fallout is repaired by that org's reconciler.
const HEADER_TOKENS = ['Routine Name', 'Routine', 'Studio', 'Entry', 'Place', 'Score'];

async function main() {
  const apply = process.argv.includes('--apply');
  const db = await openDb();

  const placeholders = HEADER_TOKENS.map(() => '?').join(',');
  const rows = await db.all(
    `SELECT a.id, a.place, a.award_type, a.performance_name, o.name AS org, e.name AS event,
            (SELECT COUNT(*) FROM award_dancers WHERE award_id = a.id AND IFNULL(source,'import') <> 'import')
          + (SELECT COUNT(*) FROM award_acknowledgements WHERE award_id = a.id)
          + (SELECT COUNT(*) FROM award_card_photos WHERE award_id = a.id)
          + (SELECT COUNT(*) FROM award_dancer_removals WHERE award_id = a.id)
          + (SELECT COUNT(*) FROM dancer_card_hidden WHERE award_id = a.id) AS attachments
       FROM awards a
       JOIN events e ON e.id = a.event_id
       JOIN organizations o ON o.id = e.org_id
      WHERE TRIM(a.performance_name) IN (${placeholders})
      ORDER BY o.name, a.id`, HEADER_TOKENS);

  if (!rows.length) { console.log('No header-row artifacts found — nothing to do.'); return; }

  const deletable = rows.filter(r => r.attachments === 0);
  const kept = rows.filter(r => r.attachments > 0);

  const byOrg = new Map();
  rows.forEach(r => byOrg.set(r.org, (byOrg.get(r.org) || 0) + 1));
  console.log(`Header-row artifacts found: ${rows.length}`);
  [...byOrg.entries()].sort((a, b) => b[1] - a[1]).forEach(([org, n]) => console.log(`  ${String(n).padStart(6)}  ${org}`));
  console.log(`\n  deletable (no user data)  ${deletable.length}`);
  console.log(`  kept (carry user data)    ${kept.length}`);
  deletable.slice(0, 10).forEach(r => console.log(`    #${r.id} [${r.award_type}] place=${r.place || '-'} "${r.performance_name}" — ${r.org} / ${r.event}`));
  if (deletable.length > 10) console.log(`    ... ${deletable.length - 10} more`);
  kept.forEach(r => console.log(`    KEPT #${r.id} "${r.performance_name}" — ${r.org} / ${r.event} (${r.attachments} attachment(s))`));

  if (!apply) { console.log('\nDRY RUN — re-run with --apply to delete.'); return; }
  if (!deletable.length) { console.log('\nNothing deletable.'); return; }

  await db.run('BEGIN IMMEDIATE');
  try {
    for (const r of deletable) {
      // FKs are intentionally OFF in this schema, so the import-source links
      // would otherwise survive their award as orphans.
      await db.run('DELETE FROM award_dancers WHERE award_id = ?', [r.id]);
      await db.run('DELETE FROM awards WHERE id = ?', [r.id]);
    }
    await db.run('COMMIT');
  } catch (e) {
    await db.run('ROLLBACK');
    throw e;
  }
  console.log(`\n✓ APPLIED: ${deletable.length} header-row artifact award(s) deleted.`);
}

main().then(() => process.exit(0)).catch(err => { console.error(err); process.exit(1); });
